server:
  port: 8081

spring:
  application:
    name: API-Authentication

  # Configuration de la source de données MySQL
  datasource:
    url: jdbc:mysql://34.248.75.185:3306/IT-Budget-DB
    username: Charles
    password: 78jXKyE65VtovYxNk5SoWdn3sV58qz
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration de JPA (Java Persistence API)
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: charles.tronel.spring@gmail.com
    password: gjew oujd wupu ojil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Token Configuration
application:
  security:
    jwt:
      secret-key: sMcZfQWkvZ7cjmvdxERDyxElXP+LBE0NfQD4V1eyJuQrJ4DsUJLsJXXHis+spgyNV3+gkLT0o8SS3HU3rDucbFeH1BB10jzqlj1jmYiwNEgpnmV/YYsm8rbRYRB+VJ6tL/01M2UhrHqQCiGmQzSbLUKiXpDiFk6G0ihCL0cCsTme82k59n2nR/95rBKnDtcurE15nEnE6IPnKa3m0XFcJ1gy9oKUAMJYdTjrQJ9kHlXkSFGxrgeRh7RgKsw4svLGLLfmH9fC9KD1Nujp2f0z3uL9BbOFyNVOQ44DjEZpeDEgnXrFaJMd4o2Efj+pCCQvGsM4Kjp4rV49ofMLj4I=
      expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true