name: Build and Deploy Docker

# Exécution de la pipeline à chaque push ou pull request sur la branche main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      # 1. Vérifier le code source dans le dépôt
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      # 2. Configurer JDK pour construire le projet Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Construire le projet avec Maven
      - name: Build with Maven
        run: mvn clean install

      # 4. Se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. Construire l’image Docker et la push
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-authentication:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-authentication:latest